### ISSUE TITLE
The system cannot find the path specified.

### ISSUE THREAD

**Issue by curlyfro** [IAMtheIAM/angular2-aot-webpack2-typescript-dotnet#1]
where's elevate?

C:\Development\TAugustine\angular2-aot-webpack2-typescript-dotnet-master>npm run onetimesetup

> Angular-2-Webpack-Typescript-DotNET-Starter@1.7.0 preonetimesetup C:\Development\TAugustine\angular2-aot-webpack2-typescript-dotnet-master
> npm run remove-web-tools

> Angular-2-Webpack-Typescript-DotNET-Starter@1.7.0 remove-web-tools C:\Development\TAugustine\angular2-aot-webpack2-typescript-dotnet-master
> cd ../PowerShell && elevate.exe -c renamer --find "External" --replace "External_DISABLED" "%ProgramFiles(x86)%/Microsoft Visual Studio 14.0/Common7/IDE/Extensions/Microsoft/Web Tools/External

**Comment by IAMtheIAM** [comment]
Thanks I forgot to add that. Its in now.

**Comment by IAMtheIAM** [comment]
If you aren't running in a visual studio environment, you dont need to run remove-web-tools. I deleted it from the master branch and moved it to the dotnet.core-1.0 branch

**Comment by curlyfro** [comment]
i'm running vs2015.  checking now.

**Comment by curlyfro** [comment]
whoops -- i didn't mean to close

**Comment by IAMtheIAM** [comment]
I'm going to update the dotnet branch now.

**Comment by curlyfro** [comment]
new error: 

> cross-env NODE_ENV=development webpack --config config/webpack.development.js --hot --profile --progress --colors --display-cached

'cross-env' is not recognized as an internal or external command,
operable program or batch file.

**Comment by IAMtheIAM** [comment]
I think it did not finish installing because the one-time-setup failed. Run this in order

`npm run clean`
'npm run onetimesetup'

**Comment by curlyfro** [comment]
same error.

**Comment by IAMtheIAM** [comment]
What is your environment? Windows version, node version, npm version?

cross-env should be globally installed, ill update the repo. This should fix it:
`npm install cross-env -g`

**Comment by IAMtheIAM** [comment]
Also FYI the AOT compilation just broke, until I fix it, use JIT compilation (devserver:jit and build:dev:jit)

**Comment by curlyfro** [comment]
i had to npm install cross-env.

windows 10, node v6.2, npm v3.8.8

**Comment by curlyfro** [comment]
ok

**Comment by IAMtheIAM** [comment]
Did you get it to run?

you need both .NET server and WDS running at the same time to load the app.

`npm run server:dotnetcore` (.net server running on port 5000)
`npm run devserver:jit` (webpack dev server running on port 4000)

Load the app from http://localhost:5000

**Comment by curlyfro** [comment]
i'm trying jit and i'm getting this error:

[default] C:\Development\TAugustine\angular2-aot-webpack2-typescript-dotnet-master\src\app-components\app\app.routes.ts:49:4
    Property 'then' does not exist on type 'string'.
[default] Checking finished with 1 errors

**Comment by IAMtheIAM** [comment]
I'll check

**Comment by IAMtheIAM** [comment]
Are you sure you got the latest version? This is the [latest version of app.routes.ts](https://github.com/IAMtheIAM/angular2-aot-webpack2-typescript-dotnet/blob/master/src/app-components/app/app.routes.ts) - there's no reference to 'then' in that file.

**Comment by curlyfro** [comment]
i'm downloaded the latest.  building now...  i'll update you in a few.

**Comment by curlyfro** [comment]
new error running npm run server:dotnetcore

can't resolve module @angular/core/src/di/metadata from C:\Development\TAugustine\angular2-aot-webpack2-typescript-dotnet-dotnet-core-1.0\index.ts
Error: can't find symbol Host exported from module C:/Development/TAugustine/angular2-aot-webpack2-typescript-dotnet-dotnet-core-1.0/node_modules/@angular/core/src/di/metadata.d.ts
    at ReflectorHost.findDeclaration (C:\Development\TAugustine\angular2-aot-webpack2-typescript-dotnet-dotnet-core-1.0\node_modules\@angular\compiler-cli\src\reflector_host.js:173:23)
    at StaticReflector.initializeConversionMap (C:\Development\TAugustine\angular2-aot-webpack2-typescript-dotnet-dotnet-core-1.0\node_modules\@angular\compiler-cli\src\static_reflector.js:147:55)
    at new StaticReflector (C:\Development\TAugustine\angular2-aot-webpack2-typescript-dotnet-dotnet-core-1.0\node_modules\@angular\compiler-cli\src\static_reflector.js:42:14)
    at Function.CodeGenerator.create (C:\Development\TAugustine\angular2-aot-webpack2-typescript-dotnet-dotnet-core-1.0\node_modules\@angular\compiler-cli\src\codegen.js:142:31)
    at codegen (C:\Development\TAugustine\angular2-aot-webpack2-typescript-dotnet-dotnet-core-1.0\node_modules\@angular\compiler-cli\src\main.js:7:36)
    at Object.main (C:\Development\TAugustine\angular2-aot-webpack2-typescript-dotnet-dotnet-core-1.0\node_modules\@angular\tsc-wrapped\src\main.js:30:16)
    at Object.<anonymous> (C:\Development\TAugustine\angular2-aot-webpack2-typescript-dotnet-dotnet-core-1.0\node_modules\@angular\compiler-cli\src\main.js:14:9)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
Compilation failed

**Comment by IAMtheIAM** [comment]
Hmm something seems weird. `npm run server:dotnetcore` simply calls `dotnet run` - do you have the dotnet core1.0 framework installed? It shouldnt be loading angular or node_module on that script.

**Comment by curlyfro** [comment]
i got the client working now.  i'm checking to make sure i have the latest dotnet core installed

**Comment by IAMtheIAM** [comment]
Great, let me know

**Comment by curlyfro** [comment]
i needed the latest .netcore.  it's working now.  thanks.

**Comment by IAMtheIAM** [comment]
excellent, you're welcome

**Comment by IAMtheIAM** [comment]
By the way, the latest commit includes working version of AOT compilation and gZip compression and serving of assets
